    pipeline {
        agent any
        stages {
            stage('Prepare Workspace') {
                steps {
                    script {
                        cleanWs()
                    }
                }
            }
        stage('SetGitUser') {
            steps {
            script {
                sh 'git config --global user.email "C-N0WB897@nomail.relay.ibm.com"'
                sh 'git config --global user.name "C-N0WB897"'
            }
            }
        }
            stage('Checkout') {
                steps {
                    withCredentials([usernamePassword(credentialsId: 'github-ci-serviceid-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_TOKEN')]) {
                        sh 'git clone https://${GIT_TOKEN}@github.ibm.com/maas360-hosted/maas360-issues.git'
                    }
                }
            }
            stage('Execute Script') {
                steps {
                    script {
                        dir('maas360-issues/evidences') {
                            sh 'cp ../issue-script.sh .'
                            sh 'sh issue-script.sh'
                            archiveArtifacts artifacts: 'unique-cve.csv', fingerprint: true
                        }
                    }
                }
            }
            stage('Git Push') {
                steps {
                    script {
                        dir('maas360-issues') {
                            sh 'git add evidences/unique-cve.csv'
                            def changes = sh(script: 'git diff --cached --exit-code', returnStatus: true)
                            if (changes == 1) {
                               sh 'git commit -m "Add CSV file generated by Jenkins job"'
                               sh 'git push origin master'
                               echo 'Changes committed and pushed.'
                            } else {
                               echo 'No changes to commit.'
                            }
                        }
                    }
                }
            }
        }
    }
